# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: dev  
  variables:
    azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
    azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: $(azure_subscription)
      azure_subscription: $(azure_subscription)
      azureresourcegroup: dcibhpdl
      workspacename: dcibhpwsdl
      azureregion: $(azureregion) 
      aksimagename: dcibhpaksdl
  
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(azure_subscription)
      azure_subscription: $(azure_subscription)
      azureresourcegroup: $(azureresourcegroup)
      workspacename: $(workspacename)
      azureregion: $(azureregion) 
      aksimagename:  $(aksimagename)

- stage: tridant
  variables:
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: $(azure_subscription)
      azure_subscription: $(azure_subscription)
      azureresourcegroup: dcibhpdl
      workspacename: dcibhpwsdl
      azureregion: $(azureregion) 
      aksimagename: dcibhpaksdl
  
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(azure_subscription)
      azure_subscription: $(azure_subscription)
      azureresourcegroup: $(azureresourcegroup)
      workspacename: $(workspacename)
      azureregion: $(azureregion) 
      aksimagename:  $(aksimagename)
