# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: dev
  jobs:
  - job: deploy
    timeoutInMinutes: 300
    cancelTimeoutInMinutes: 2
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureregion: $(azureregion) 
      project: "e2etestharness"
    strategy:
      matrix:
        DLAKSDeployAMLJob:
          deployment_name: DLAKSDeployAMLJob 
          template: DLAKSDeployAMLJob.yml
          azureresourcegroup: dcibhprgdl
          workspacename: dcibhpwsdl
          aksimagename: dcibhpaksdl
        MLAKSDeployAMLJob:
          deployment_name: MLAKSDeployAMLJob
          template: MLAKSDeployAMLJob.yml
          azureresourcegroup: dcibhprg
          workspacename: dcibhpws
          aksimagename:  dcibhpaks    
    steps:
    - template: .ci/steps/deploy_step.yml
      parameters:
        deployment_name: $(deployment_name)
        template: $(template)
        azureSubscription: $(azureSubscription)
        azureresourcegroup: $(azureresourcegroup)
        location: $(azureregion)
        project : $(project)
        azure_subscription: $(azure_subscription)
        workspacename: $(workspacename)
        azureregion: $(azureregion)
        aksimagename: $(aksimagename)

- stage: staging
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: staging-pydl
      workspacename: stagingpydl
      azureregion: $(azureregion) 
      aksimagename:  staginghpaks
      project: "e2etestharness" 


- stage: tridant
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: tridant-pydl
      workspacename: tridantpydl
      azureregion: $(azureregion) 
      aksimagename: tridantpydlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
  
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: tridant-pyml
      workspacename: tridantpy
      azureregion: $(azureregion) 
      aksimagename:  tridantpymlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
