# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: dev
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: dcibhprgdl
      workspacename: dcibhpwsdl
      azureregion: $(azureregion) 
      aksimagename: dcibhpaksdl
      project: "e2etestharness"

  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: dcibhprg
      workspacename: dcibhpws
      azureregion: $(azureregion) 
      aksimagename:  dcibhpaks
      project: "e2etestharness" 

- stage: staging
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734 (0ca618d2-22a8-413a-96d0-0f1b531129c3)'
      azure_subscription: 0ca618d2-22a8-413a-96d0-0f1b531129c3
      azureresourcegroup: staging-pydl
      workspacename: stagingpydl
      azureregion: $(azureregion) 
      aksimagename:  staginghpaks
      project: "e2etestharness" 


- stage: tridant
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734 (0ca618d2-22a8-413a-96d0-0f1b531129c3)'
      azure_subscription: 0ca618d2-22a8-413a-96d0-0f1b531129c3
      azureresourcegroup: tridant-pydl
      workspacename: tridantpydl
      azureregion: $(azureregion) 
      aksimagename: tridantpydlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)

  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734 (0ca618d2-22a8-413a-96d0-0f1b531129c3)'
      azure_subscription: 0ca618d2-22a8-413a-96d0-0f1b531129c3
      azureresourcegroup: tridant-pyml
      workspacename: tridantpy
      azureregion: $(azureregion) 
      aksimagename:  tridantpymlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
