# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: dev
  jobs:
  - job:
    strategy:
      maxParallel: 1
      matrix:
        WESTUS2: 
          azureregion: westus2
        WESTUS:
          azureregion: westus
    steps: 
      - template: .ci/steps/deploy.yml
        parameters:
          deployment_name: DLAKSDeployAMLJob
          template: DLAKSDeployAMLJob.yml
          azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
          azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
          azureresourcegroup: dcibhprgdl
          workspacename: dcibhpwsdl
          azureregion: $(azureregion) 
          aksimagename: dcibhpaksdl
          project: "e2etestharness"

      - template: .ci/steps/deploy.yml
        parameters:
          deployment_name: MLAKSDeployAMLJob
          template: MLAKSDeployAMLJob.yml
          azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
          azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
          azureresourcegroup: dcibhprg
          workspacename: dcibhpws
          azureregion: $(azureregion) 
          aksimagename:  dcibhpaks
          project: "e2etestharness" 

- stage: staging
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: staging-pydl
      workspacename: stagingpydl
      azureregion: $(azureregion) 
      aksimagename:  staginghpaks
      project: "e2etestharness" 


- stage: tridant
  jobs:
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: tridant-pydl
      workspacename: tridantpydl
      azureregion: $(azureregion) 
      aksimagename: tridantpydlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
  
  - template: .ci/steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: 'AICAT-VB-E2E (989b90f7-da4f-41f9-84c9-44848802052d)'
      azure_subscription: 989b90f7-da4f-41f9-84c9-44848802052d
      azureresourcegroup: tridant-pyml
      workspacename: tridantpy
      azureregion: $(azureregion) 
      aksimagename:  tridantpymlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
