# MLAKSDeploy Pipeline

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - Python-ML-RealTimeServing/*

pr:
  branches:    
    include:
    - master
  paths:
   include:
     - Python-Keras-RealTimeServing/* 

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

variables:
  deployment_name: ''
  template: ''
  azureSubscription: ''
  azure_subscription: ''
  azureresourcegroup: ''
  workspacename: ''
  azureregion: ''
  aksimagename: ''
  environment: 'tridant-ai'
  doCleanup: True
  alias: '-'
  project: '-'
  expires : "2019-08-01"
  agent: 'AI-GPU'


jobs:
- job: MLAKSDeployAMLJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  
  - template: createResourceGroupTemplate.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      azureresourcegroup: ${{parameters.azureresourcegroup}}
      location: ${{parameters.azureregion}}
      alias : ${{parameters.alias}}
      project : ${{parameters.project}}
      expires : ${{parameters.expires}}

  - template: config_conda.yml
    parameters:
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 00_AMLSetup.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}
      azure_subscription: ${{parameters.azure_subscription}}
      azureresourcegroup: ${{parameters.azureresourcegroup}}
      workspacename: ${{parameters.workspacename}}
      azureregion: ${{parameters.azureregion}}
      aksimagename: ${{parameters.aksimagename}}

  - template: azpapermill.yml
    parameters:
      notebook: 01_DataPrep.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 02_TrainOnLocal.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 03_DevelopScoringScript.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 04_BuildImage.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 05_DeployOnAKS.ipynb
      location: ${{parameters.location}}/aks
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}
      aks_name: ${{parameters.aks_name}}
      aks_location: ${{parameters.azureregion}}
      aks_service_name: ${{parameters.aks_service_name}}
      python_path: "$(System.DefaultWorkingDirectory)/Python-ML-RealTimeServing/{{cookiecutter.project_name}}/"

  - template: azpapermill.yml
    parameters:
      notebook: 06_SpeedTestWebApp.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 07_RealTimeScoring.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - template: azpapermill.yml
    parameters:
      notebook: 08_TearDown.ipynb
      location: ${{parameters.location}}
      azureSubscription: ${{parameters.azureSubscription}}
      conda: ${{parameters.conda}}

  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate MLAKSDeployAML
      echo Execute Resource Group Delete
      existResponse=$(az group exists -n $(azureresourcegroup))
      if [ "$existResponse" == "true" ]; then
        echo Deleting project resource group
        az group delete --name $(azureresourcegroup) --yes
      else
        echo Project resource group did not exist
      fi
      echo Done Cleanup
    displayName: 'Backup Cleanup'
    condition: or(canceled(),failed())
