parameters:
  Agent: Hosted Ubuntu 1604
  stageName: 'defaultStageName'
  jobDisplayName: 'defaultDisplayName'
  jobTimeoutInMinutes: 180
  TridentWorkloadTypeShort: #
  DeployLocation: #
  TestPostfix: # "" | "-release" | "-preview"
  Deploy_Location_Short: #
  DefaultWorkingDirectory: #
  Template: #
  aksimagename: #
  ProjectLocation: #
  PythonPath: #
  cluster_name: #
  flighting_release: false
  flighting_preview: false
  doCleanup: False
  sub_vars: ../vars/agce_devops_sub_vars.yml
  workload_vars: #

stages:
- stage: ${{parameters.stageName}}
  dependsOn: []    
  jobs:
  - job: deploy_notebook_steps
    displayName: ${{parameters.jobDisplayName}}

    pool:
      name: ${{parameters.Agent}}
  
    timeoutInMinutes: ${{parameters.jobTimeoutInMinutes}}
  
    workspace:
      clean: all
  
    variables:
    - template: ${{parameters.sub_vars}}
    - template: ${{parameters.workload_vars}}
  
    steps:
    - template: ../steps/deploy_notebook_steps_v2.yml
      parameters:
        template: ${{parameters.Template}}
        azureSubscription: ${{variables.azureSubscription}}
        azure_subscription: ${{variables.azure_subscription}}
        azureresourcegroup: ${{parameters.TridentWorkloadTypeShort}}-${{parameters.DeployLocation}}${{parameters.TestPostfix}}
        workspacename: ${{parameters.TridentWorkloadTypeShort}}-${{parameters.DeployLocation}}
        azureregion: ${{parameters.DeployLocation}}
        aksimagename: ${{parameters.aksimagename}}
        aks_name: ${{parameters.TridentWorkloadTypeShort}}${{parameters.TestPostfix}}
        location: ${{parameters.ProjectLocation}}
        python_path: ${{parameters.DefaultWorkingDirectory}}${{parameters.PythonPath}}
        cluster_name: ${{parameters.TridentWorkloadTypeShort}}${{parameters.TestPostfix}}
        flighting_release: ${{parameters.flighting_release}}
        flighting_preview: ${{parameters.flighting_preview}}
        doCleanup: ${{parameters.doCleanup}}
