# AI Architecture Template TODO: update tile
#
# A Github Service Connection must also be created with the name "AIArchitecturesAndPractices-GitHub"
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml
#
# An Agent_Name Variable must be creating in the Azure DevOps UI.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
#
# This must point to an Agent Pool, with a Self-Hosted Linux VM with a Docker.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops

parameters:
  azureSubscription: ''
  azure_subscription: ''
  azureresourcegroup: ''
  workspacename: ''
  azureregion: westus2
  aksimagename: ''
  aks_name: ''
  aks_service_name: myimage
  conda: ''
  doCleanup: true
  flighting_release: false
  flighting_preview: false
  flighting_master: false
  fresh_install: false
  sql_server_name: "x"
  sql_database_name: "x"
  sql_username: "x"
  sql_password: "x"
  datastore_rg: "x"
  container_name: "x"
  account_name: "x"
  account_key: "x"

steps:
- template: config_conda.yml
  parameters:
    conda_location: .
    azureSubscription: ${{parameters.azureSubscription}}
    conda: ${{parameters.conda}}
    flighting_release: ${{parameters.flighting_release}}
    flighting_preview: ${{parameters.flighting_preview}}
    flighting_master: ${{parameters.flighting_master}}
    fresh_install: ${{parameters.fresh_install}}

- template: pytest_steps.yml
  parameters:
    azureSubscription: ${{parameters.azureSubscription}}
    azure_subscription: ${{parameters.azure_subscription}}
    azureresourcegroup: ${{parameters.azureresourcegroup}}    
    workspacename: ${{parameters.workspacename}}
    conda: ${{parameters.conda}}
    azureregion: ${{parameters.azureregion}}
    sql_server_name: ${{parameters.sql_server_name}}
    sql_database_name: ${{parameters.sql_database_name}}
    sql_username: ${{parameters.sql_username}}
    sql_password: ${{parameters.sql_password}}
    aksimagename: ${{parameters.aksimagename}}
    aks_service_name: ${{parameters.aks_service_name}}
    aks_name: ${{parameters.aks_name}}
    datastore_rg: ${{parameters.datastore_rg}}
    container_name: ${{parameters.container_name}}
    account_name: ${{parameters.account_name}}
    account_key: ${{parameters.account_key}}

- template: cleanuptask.yml
  parameters:
    azureSubscription: ${{parameters.azureSubscription}}
    azure_subscription: ${{parameters.azure_subscription}}
    conda: ${{parameters.conda}}
    azureresourcegroup: ${{parameters.azureresourcegroup}}
    doCleanup: ${{parameters.doCleanup}}
