  
parameters:
  conda_location: '.'#
  azureSubscription: #
  conda: #
  backward_compatability: false
  backward_version: 1.0.2
  flighting_release: false
  flighting_preview: false

steps:
- task: AzureCLI@1
  displayName: 'Add Conda to Path'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    scriptLocation: inlineScript
    inlineScript: 'echo "##vso[task.prependpath]$CONDA/bin"'

- task: AzureCLI@1
  displayName: 'Setup Conda'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      conda env create -f ${{parameters.conda_location}}/environment.yml --force
      source activate ${{parameters.conda}}

- task: AzureCLI@1
  displayName: 'Downgrade AML SDK to previous release'
  condition: eq('${{ parameters.backward_compatability }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}      
      pip install -U azureml-sdk[notebooks,contrib]==${{parameters.backward_version}}

- task: AzureCLI@1
  displayName: 'Upgrade AML SDK to latest release'
  condition: eq('${{ parameters.flighting_release }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}      
      pip install -U azureml-sdk[notebooks,contrib]

- task: AzureCLI@1
  displayName: 'Upgrade AML SDK to pre-release'
  condition: eq('${{ parameters.flighting_preview }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}    
      pip install -U azureml-sdk[notebooks,contrib] \
        --index-url https://azuremlsdktestpypi.azureedge.net/sdk-release/Preview/E7501C02541B433786111FE8E140CAA1 \
        --extra-index-url https://pypi.python.org/simple
      
      
