  
parameters:
  conda_location: '.'#
  azureSubscription: #
  conda: #
  flighting_release: false
  flighting_preview: false


steps:
- task: AzureCLI@1
  displayName: 'Add Conda to Path'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    scriptLocation: inlineScript
    inlineScript: 'echo "##vso[task.prependpath]$CONDA/bin"'

- task: AzureCLI@1
  displayName: 'Setup Conda'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      conda env create -f ${{parameters.conda_location}}/environment.yml --force
      source activate ${{parameters.conda}}

- task: AzureCLI@1
  displayName: 'Setup Conda'
  condition: eq('${{ parameters.flighting_release }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      conda env create -f ${{parameters.conda_location}}/environment.yml --force
      source activate ${{parameters.conda}}

- task: AzureCLI@1
  displayName: 'Setup Conda'
  condition: eq('${{ parameters.flighting_preview }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      conda env create -f ${{parameters.conda_location}}/environment.yml --force
      source activate ${{parameters.conda}}
