  
parameters:
  conda_location: #
  azureSubscription: #
  conda: #


steps:
- task: AzureCLI@1
  displayName: 'Add Conda to Path'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    scriptLocation: inlineScript
    inlineScript: 'echo "##vso[task.prependpath]$CONDA/bin"'

- task: AzureCLI@1
  displayName: 'Setup Conda'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    scriptLocation: inlineScript
    inlineScript: |
      conda env create -f ${{parameters.conda_location}}/environment.yml
      source ~/anaconda3/etc/profile.d/conda.sh
      conda activate ${{parameters.conda}}
