parameters:
  azureresourcegroup: "dcibrg"
  workspacename: "dcibws"
  azureregion: "westus"
  aksimagename: "myimage"
  aks_name: "dcibaksname"
  aks_service_name: "dcibaksserv"
  acr_name: "x"
  CRAN: 'https://cloud.r-project.org'
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  
steps:
- script: sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev
  displayName: "Install System Dependencies"

- bash: |
    echo "options(repos = '${{parameters.CRAN}}')" > ~/.Rprofile
    echo ".libPaths(c('${{parameters.R_LIBS_USER}}', .libPaths()))" >> ~/.Rprofile
    mkdir -p ${{parameters.R_LIBS_USER}}
  displayName: 'Setup R library directory'

- bash: |
    Rscript -e "pkgs <- c('remotes', 'rcmdcheck', 'drat', 'AzureGraph'); if(length(find.package(pkgs, quiet=TRUE)) != length(pkgs)) install.packages(pkgs)"
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'
