parameters:
  azureresourcegroup: "dcibrg"
  workspacename: "dcibws"
  azureregion: "westus"
  aksimagename: "myimage"
  aks_name: "dcibaksname"
  aks_service_name: "dcibaksserv"
  acr_name: "x"
  
steps:
- bash: |
    echo "Setup R"
    sudo Rscript ./setup.R
