  
parameters:
  conda_location: '.'#
  azureSubscription: #
  conda: #
  backward_compatability: false
  backward_version: 1.0.2
  flighting_release: false
  flighting_preview: false
  flighting_master: false

steps:
- task: AzureCLI@1
  displayName: 'Add Conda to Path'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    scriptLocation: inlineScript
    inlineScript: 'echo "##vso[task.prependpath]$CONDA/bin"'

- task: AzureCLI@1
  displayName: 'Setup Conda'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      conda update --force-reinstall -y -n base -c defaults conda
      conda env create -f ${{parameters.conda_location}}/environment.yml python=3.6 --force
      source activate ${{parameters.conda}}

- task: AzureCLI@1
  displayName: 'Upgrade AML SDK to latest release'
  condition: eq('${{ parameters.flighting_release }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}

      pip install -U azureml-sdk[notebooks,contrib]
      
- task: AzureCLI@1
  displayName: 'Upgrade AML SDK to Candidate release'
  condition: eq('${{ parameters.flighting_preview }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}

      pip install -U azureml-sdk[notebooks,contrib] \
        --extra-index-url https://azuremlsdktestpypi.azureedge.net/sdk-release/Candidate/604C89A437BA41BD942B4F46D9A3591D

- task: AzureCLI@1
  displayName: 'Upgrade AML SDK to master release'
  condition: eq('${{ parameters.flighting_master }}', true)
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    failOnStandardError: True
    scriptLocation: inlineScript
    inlineScript: |
      source activate ${{parameters.conda}}   

      pip uninstall -y                  \
        azureml-sdk                     \
        azureml-core                    \
        azureml-widgets                 \
        azureml-train-automl-client     \
        azureml-contrib-pipeline-steps  \
        azureml-contrib-notebook        \
        azureml-contrib-services        \
        azureml-contrib-tensorboard     \
        azureml-contrib-server          \
        azureml-contrib-run             \
        azureml-contrib-brainwave

      pip install -U "azureml-sdk[notebooks,contrib]<1.0" \
        --extra-index-url https://azuremlsdktestpypi.azureedge.net/sdk-release/master/588E708E0DF342C4A80BD954289657CF

