parameters:
  azureresourcegroup: "dcibrg"
  workspacename: "dcibws"
  azureregion: "westus"
  aksimagename: "myimage"
  aks_name: "dcibaksname"
  aks_service_name: "dcibaksserv"
  acr_name: "x"
  
steps:
- bash: |
    echo "options(repos = '$(cranRepo)')" > ~/.Rprofile
    echo ".libPaths(c('$R_LIBS_USER', .libPaths()))" >> ~/.Rprofile
    mkdir -p $R_LIBS_USER
  displayName: 'Setup R library directory'

- bash: |
    Rscript -e "pkgs <- c('remotes', 'rcmdcheck', 'drat'); if(length(find.package(pkgs, quiet=TRUE)) != length(pkgs)) install.packages(pkgs)"
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'
