parameters:
  root: /data/anaconda/bin
  conda_env: # this param must be set

steps:
- bash: |
    echo "##vso[task.prependpath]${{parameters.root}}"
    conda env list
  displayName: 'Add Conda to PATH'

- script: |
    conda env remove -n ${{parameters.conda_env}}
    python ./scripts/generate_conda_file.py --name ${{parameters.conda_env}}
    conda env create --quiet -f ${{parameters.conda_env}}.yaml 2> log
  displayName: 'Setup Conda Env'
  failOnStandardError: True
