parameters:  
  Agent: Hosted Ubuntu 1604
  Demands: "python3"
  jobTimeoutInMinutes: 180
  jobDisplayName: 'defaultDisplayName'
  TridentWorkloadTypeShort: #
  DeployLocation: #
  DefaultWorkingDirectory: #
  Template: #
  ProjectLocation: #
  PythonPath: #
  workload_vars: #
  doCleanup: True
  flighting_release: true
  flighting_preview: true

stages:
- template: ../stage/deploy_notebooks_stage_v2.yml
  parameters:
    Agent: ${{parameters.Agent}}
    Demands: ${{parameters.Demands}}
    stageName: 'stable'
    jobDisplayName: ${{parameters.jobDisplayName}}
    jobTimeoutInMinutes: ${{parameters.jobTimeoutInMinutes}}
    TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
    DeployLocation: ${{parameters.DeployLocation}}
    TestPostfix: "-stable"
    DefaultWorkingDirectory: ${{parameters.DeployLocation}}
    Template: ${{parameters.Template}}
    ProjectLocation: ${{parameters.ProjectLocation}}
    PythonPath: ${{parameters.PythonPath}}
    workload_vars: ${{parameters.workload_vars}}
    doCleanup: ${{parameters.doCleanup}}
    
- ${{ if eq(parameters.flighting_release, 'true') }}:
  - template: ../stage/deploy_notebooks_stage_v2.yml
    parameters:
      Agent: ${{parameters.Agent}}
      Demands: ${{parameters.Demands}}
      stageName: 'release'
      jobDisplayName: ${{parameters.jobDisplayName}}
      TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
      DeployLocation: ${{parameters.DeployLocation}}
      TestPostfix: "-release"
      DefaultWorkingDirectory: ${{parameters.DeployLocation}}
      Template: ${{parameters.Template}}
      ProjectLocation: ${{parameters.ProjectLocation}}
      PythonPath: ${{parameters.PythonPath}}
      flighting_release: true
      workload_vars: ${{parameters.workload_vars}}
      doCleanup: ${{parameters.doCleanup}}

- ${{ if eq(parameters.flighting_preview, 'true') }}:
  - template: ../stage/deploy_notebooks_stage_v2.yml
    parameters:
      Agent: ${{parameters.Agent}}
      Demands: ${{parameters.Demands}}
      stageName: 'preview'
      jobDisplayName: ${{parameters.jobDisplayName}}
      TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
      DeployLocation: ${{parameters.DeployLocation}}
      TestPostfix: "-preview"
      DefaultWorkingDirectory: ${{parameters.DeployLocation}}
      Template: ${{parameters.Template}}
      ProjectLocation: ${{parameters.ProjectLocation}}
      PythonPath: ${{parameters.PythonPath}}
      flighting_preview: true
      workload_vars: ${{parameters.workload_vars}}
      doCleanup: ${{parameters.doCleanup}}
