parameters:  
  Agent: Hosted Ubuntu 1604
  jobTimeoutInMinutes: 180
  jobDisplayName: 'defaultDisplayName'
  TridentWorkloadTypeShort: #
  DeployLocation: #
  DefaultWorkingDirectory: #
  Template: #
  ProjectLocation: #
  PythonPath: #
  doCleanup: False

stages:
- template: ../stage/deploy_notebooks_stage_v2.yml
  parameters:
    Agent: ${{parameters.Agent}}
    stageName: 'stable'
    jobDisplayName: ${{parameters.jobDisplayName}}
    jobTimeoutInMinutes: ${{parameters.jobTimeoutInMinutes}}
    TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
    DeployLocation: ${{parameters.DeployLocation}}
    TestPostfix: "-stable"
    DefaultWorkingDirectory: ${{parameters.DeployLocation}}
    Template: ${{parameters.Template}}
    ProjectLocation: ${{parameters.ProjectLocation}}
    PythonPath: ${{parameters.PythonPath}}
    doCleanup: ${{parameters.doCleanup}}

- template: ../stage/deploy_notebooks_stage_v2.yml
  parameters:
    Agent: ${{parameters.Agent}}
    stageName: 'release'
    jobDisplayName: ${{parameters.jobDisplayName}}
    TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
    DeployLocation: ${{parameters.DeployLocation}}
    TestPostfix: "-release"
    DefaultWorkingDirectory: ${{parameters.DeployLocation}}
    Template: ${{parameters.Template}}
    ProjectLocation: ${{parameters.ProjectLocation}}
    PythonPath: ${{parameters.PythonPath}}
    flighting_release: true
    doCleanup: ${{parameters.doCleanup}}

- template: ../stage/deploy_notebooks_stage_v2.yml
  parameters:
    Agent: ${{parameters.Agent}}
    stageName: 'preview'
    jobDisplayName: ${{parameters.jobDisplayName}}
    TridentWorkloadTypeShort: ${{parameters.TridentWorkloadTypeShort}}
    DeployLocation: ${{parameters.DeployLocation}}
    TestPostfix: "-preview"
    DefaultWorkingDirectory: ${{parameters.DeployLocation}}
    Template: ${{parameters.Template}}
    ProjectLocation: ${{parameters.ProjectLocation}}
    PythonPath: ${{parameters.PythonPath}}
    flighting_preview: true
    doCleanup: ${{parameters.doCleanup}}
